#include "function_traits.hpp"
#include <cmath>


extern const std::vector<dynamic_symbol> libm_symbols = {
    { "acos", acos },
    { "acosf", acosf },
    { "asin", asin },
    { "asinf", asinf },
    { "atan", atan },
    { "atan2", atan2 },
    { "atan2f", atan2f },
    { "atanf", atanf },
    { "cbrt", cbrt },
    { "cos", cos },
    { "cosf", cosf },
    { "cosh", cosh },
    { "coshf", coshf },
    { "erfcf", erfcf },
    { "exp", exp },
    { "exp2", exp2 },
    { "exp2f", exp2f },
    { "expf", expf },
    { "expm1", expm1 },
    { "fmod", fmod },
    { "fmodf", fmodf },
    { "frexp", frexp },
    { "frexpf", frexpf },
    { "hypotf", hypotf },
    { "ldexp", ldexp },
    { "ldexpf", ldexpf },
    { "log", log },
    { "log10", log10 },
    { "log10f", log10f },
    { "log2", log2 },
    { "log2f", log2f },
    { "logbf", logbf },
    { "logf", logf },
    { "modf", modf },
    { "modff", modff },
    { "nan", nan },
    { "nextafterf", nextafterf },
    { "pow", pow },
    { "powf", powf },
    { "scalbnf", scalbnf },
    { "sin", sin },
    { "sincos", sincos },
    { "sincosf", sincosf },
    { "sinf", sinf },
    { "sinh", sinh },
    { "tan", tan },
    { "tanf", tanf },
    { "tanh", tanh },
    { "tanhf", tanhf }
};
